# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i015LamwHgsRQ-yl4pzisprW1VK-EqGT
"""

!pip install streamlit pyngrok pandas openpyxl

import pandas as pd

# Load data
df = pd.read_excel("/content/Master Bot ok or notok (1).xlsx")

def get_invoice_status(invoice_no):
    result = df[df['Invoice_No'] == invoice_no]

    if result.empty:
        return "❌ Invoice not found. Please check the number."

    row = result.iloc[0]

    return f"""
    ✅ Invoice Details:

    Vendor ID: {row['Vendor_ID']}
    Invoice No: {row['Invoice_No']}
    Due Date: {row['Due_Date']}
    Status: {row['Status']}
    Remarks: {row['Remarks']}
    """

def chatbot():
    print("🤖 Vendor Payment Chatbot")
    print("Type your Invoice Number (or type 'exit')")

    while True:
        user_input = input("You: ")

        if user_input.lower() == "exit":
            print("Bot: Thank you!")
            break

        response = get_invoice_status(user_input)
        print("Bot:", response)

import streamlit as st
import pandas as pd

df = pd.read_excel("/content/Master Bot ok or notok (1).xlsx")

st.title("💼 Vendor Payment Status Chatbot")

invoice_no = st.text_input("Enter Invoice Number")

if st.button("Check Status"):
    result = df[df['Invoice_No'] == invoice_no]

    if result.empty:
        st.error("Invoice not found ❌")
    else:
        row = result.iloc[0]
        st.success("Invoice Found ✅")

        st.write("**Vendor ID:**", row['Vendor_ID'])
        st.write("**Due Date:**", row['Due_Date'])
        st.write("**Status:**", row['Status'])
        st.write("**Remarks:**", row['Remarks'])

!streamlit run app.py &>/dev/null &

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("🤖 Vendor Payment Chatbot")
# 
# invoice = st.text_input("Enter Invoice Number")
# 
# if invoice:
#     st.success(f"Checking status for {invoice}")

from pyngrok import ngrok

ngrok.set_auth_token("3BqFLlYuI7BPZa4lhI4UFyut8WQ_6zYMGzuGXYmaoJih3nQbR")

!streamlit run app.py --server.port 8501 &>/dev/null &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print("Your App Link:", public_url)

!jupyter nbconvert --to script your_notebook.ipynb